spring:
  application:
    name: invoking-method
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8080/dev
    username: admin
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
server:
  port: 8088